server:
  port: 6002

nacos:
  server-address: 127.0.0.1
  port: 8848
  username: nacos
  password: nacos

spring:
  application:
    name: nacos-dubbo-consumer-demo
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  main:
    allow-bean-definition-overriding: true
dubbo:
  scan:
    base-packages: site.paranoia.user
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://${nacos.server-address}:${nacos.port}/?username=${nacos.username}&password=${nacos.password}
  cloud:
    subscribed-services: nacos-dubbo-provider-demo



